apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: minio-tenant-service-scrape
spec:
  selector:
    matchLabels:
      v1.min.io/tenant: {{ .Values.metrics.tenantName}}
  endpoints:
    - port: http-minio
      scheme: https
      path: /minio/v2/metrics/cluster
      tlsConfig:
        insecureSkipVerify: true